### ISSUE TITLE
Uncaught exception 'GoogleUrl\Exception\CurlException' with message 'HTTP query failled [curl-error : 60 - SSL certificate problem: unable to get local issuer certificate ]

### ISSUE THREAD

**Issue by fjhadz1** [gsouf/google-url#34]
Hi,
I'm new about scraping. I copied your code in example of use. Then on I've encounter this error. 

> Fatal error: Uncaught exception 'GoogleUrl\Exception\CurlException' with message 'HTTP query failled [curl-error : 60 - SSL certificate problem: unable to get local issuer certificate ] for the following URL : https://www.google.com/search?q=acdc&start=0&num=10&complete=0&pws=0&hl=en&lr=lang_en' in C:\wamp\www\google-url-master\lib\GoogleUrl.php on line 360 

I really don't know how to start fixing it and I really appreciate if you could help me regarding this matter. Thanks

**Comment by gsouf** [comment]
Hi,

This issue is not related with the library, that's a CURL error. It seems that CURL library cant establish the secure connection with google. 

Are you on windows? That could be a bug or a problem  with curl itself.

Someone tells that it could fix this issue by [installing CURL again](http://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate): 

> On windows I was having this problem. Curl was installed by mysysgit, so downloading and installing the newest version fixed my issue.

**Comment by fjhadz1** [comment]
Thank you so much. Yes I am using windows. I did fix the problem by installing cacert.pem in my php extension in wamp.

Thank you master gsouf  this google URL scraper script really help a lot of beginners like me. :)

**Comment by gsouf** [comment]
You're welcome ;)
