### ISSUE TITLE
Retrieve IP from proxy provider (paid subscription) and Automatically store it on the proxylist

### ISSUE THREAD

**Issue by fjhadz1** [gsouf/google-url#35]
Hi,
Just want to ask if it would be possible to retrieve IP from a proxy provider using a script and automatically store it on the proxy list? 

I'm really new about this stuff and I really appreciate if you can help me out.
Thanks.

**Comment by gsouf** [comment]
Hi, 

That's a very specific question, the library offers tools to manipulate proxies, then it's up to you to store proxy at your convenience. I'm afraid I can't help you much for this point.

When you tell "retrieve IP from a proxy provider using a script and automatically store it on the proxy list?" Yes it is possible, but only if the proxy provider provides an API to retrive proxy IPs.


PS: I'm going to deprecate the usage of the proxypool offered by the library because it's out of scope of parsing google and proxy management should depend on the plateform and not on the library.

**Comment by fjhadz1** [comment]
Thanks Master Gsouf for your reply.
Do you know any reliable proxy provider that offers API? To link your code on to.

**Comment by gsouf** [comment]
I cant advice you a good proxy provider, I didn't use proxy recently. Currently I'm only using the script at a very small scale and I don't need a proxy.

**Comment by gsouf** [comment]
I'm closing the issue, if you have any input feel free to open it again
