### ISSUE TITLE
HTTP query failed [Curl-error:35]

### ISSUE THREAD

**Issue by fjhadz1** [gsouf/google-url#36]
Hi,
I just want to ask regarding this problem.

HTTP query failled [curl-error : 35 - Unknown SSL protocol error in connection to ipv4.google.com:443 ]

I've already been testing the application for about a week and seems great (no longer encountered a problem) but then just today I've encountered this error.

I already searched for a few solutions and found some here: 
http://blogs.agilefaqs.com/2013/11/25/curl-35-unknown-ssl-protocol-error-in-connection/

and according to that source I need to add this: 
curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

It seems that I'am new to OOCurl and Don't know where to add this thing/ basically fix this problem.

I really appreciate if you can help me with this. Thank you.

**Comment by gsouf** [comment]
Hi,
Before trying to fix it from php, would you want to try to fix it from your system ?  Did you upgrade curl, or used a different environment ? Maybe your curl install has a problem, (are you on windows ? Some versions of curl fail on windows)

**Comment by fjhadz1** [comment]
Yes, I'm currently using Windows 7 and  WAMP as my server.. I did not manage to upgrade Curl (OOCurl) which is in this library. Basically I just use your script and add a few tweaks and also some proxy.

**Comment by gsouf** [comment]
You are confusing the CURL library, that is installed in your system, and the CURL wrapper that is shipped shipped with the library (OOCurl) and that uses the CURL library installed on your system.

When I tell about upgrading curl, I mean the one on your system. Curl on windows is known to have some bugs in some cases.

Well, if you want to tryth fix you found:
``curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);``

Here is how you can do it manually (but I dont advice you to do this because you wont be able to do future updates of the library):

- open the following file on the following line:  https://github.com/gsouf/google-url/blob/master/lib/GoogleUrl.php#L315
- Add the following content:

``$c->ipresolve = CURL_IPRESOLVE_V4;``
``

**Comment by fjhadz1** [comment]
Thank you so much. I will try to test it later. and also upgrade the curl which is on my system. I'll update you as soon as possible regarding the results. 

Once again thank you so much.

**Comment by fjhadz1** [comment]
Hi, It seems that the problem occurs again and the solution on adding the " $c->ipresolve = CURL_IPRESOLVE_V4;" did not fix it. Do you know an alternate solution to fix this problem?. 
Thankz.

**Comment by gsouf** [comment]
As I stated before the problem is not with the library itself, but with curl. It's hard for me to know where the problem comes from. Did you try to run your script on a different environment ?

**Comment by fjhadz1** [comment]
I'm sorry about that, I'm quite new about this stuff. No, i did not able to run the script on a different environment. In addition the script just work fine today in my first run and got this problem again on the 2nd run..

**Comment by gsouf** [comment]
Weird... maybe something like a cache after the first run, maybe in the dns, I dont know.

I don't know if it's valid on windows, but can you run this in you command line:

``curl -v https://www.google.fr``
